### ISSUE TITLE
Usage of short numbers

### ISSUE THREAD

**Issue by brunoamancio** [kaisermann/svelte-i18n#14]
Is it possible to format numbers with B for billion, M for million, K for thousands?

For example, 3200000 shoud be 3,2M

**Comment by kaisermann** [comment]
Currently there's no way of formatting numbers with a compact notation (look for compact [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat)). It seems that this API is experimental, so `intl-formatmessage` doesn't offer support for it. 

For now, I can expose an API to create custom formatters to the user-land. To do this, it'd probably be a breaking-change, since I'd need to modify the signature of the `_` methods.

**Comment by kaisermann** [comment]
Something like: 

1) When initialising the i18n store, add some custom formats (`number` or `date` or `time`). The format props will be passed directly to the `Intl.NumberFormat` or `Intl.DateTimeFormat`.

![image](https://user-images.githubusercontent.com/12702016/68633347-52f94d00-04d0-11ea-8bc4-239b45288c19.png)

2) On your template, call the `_.number` method specifying the `format`: 

```Number util: {$_.number(10000, { format: 'compact' })}`

**Comment by kaisermann** [comment]
This change can bring some flexibility, but it includes having to rewrite all interpolated translations from:

`$_('path.to.message', { name: 'John', lastname: 'Doe' })`

to 

`$_('path.to.message', { values: { name: 'John', lastname: 'Doe' }})`

**Comment by kaisermann** [comment]
Played around a bit and you can test a version of what I said above in the https://github.com/kaisermann/svelte-i18n/tree/feat/options-object branch.

**Comment by brunoamancio** [comment]
It's more flexible with the ability to include custom formats :) The breaking changes could also released in a new version, so people using the older signatures can explicitaly migrate, if needed.
