### ISSUE TITLE
2.0.2 removed from npm and 2.1.0 breaks in EdgeHTML

### ISSUE THREAD

**Issue by TorstenDittmann** [kaisermann/svelte-i18n#26]
**Describe the bug**
2.0.2 went missing on npm and upgrading to 2.1.0 breaks EdgeHTML for me.

![__VirtualBox_Windows 10 Enterprise_02_12_2019_16_26_24](https://user-images.githubusercontent.com/1759475/69972093-468d7080-1521-11ea-95ef-9bdd49cdf175.png)
![_VirtualBox_Windows 10 Enterprise_02_12_2019_16_26_24](https://user-images.githubusercontent.com/1759475/69972094-47260700-1521-11ea-9c92-d3366498b9d0.png)

Sadly I am on the go right now and cant properly debug with my virtual machine on my laptop.

EDIT:
Just found a very very stupid typo of mine that somehow only led to an error in Edge.

EDIT2: 
Due to cache stuff the error was fixed by an old version. Error still occurs.

**Comment by kaisermann** [comment]
@TorstenDittmann I've (mistakenly) removed the previous `v2` versions from npm in less than a day of publishing, that's why you can't see them anymore. They were badly tested and had a few nasty bugs 😢.

I think the destructuring assignment along with a spread is what's breaking your build: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Browser_compatibility

I'll take a look at it and see if I can change it to a more supported syntax. For now you can transpile your components with some tool like babel.

**Comment by TorstenDittmann** [comment]
Ah that is great to hear :)

**Comment by kaisermann** [comment]
The `MSEdge` virtual machine is still downloading here, but I've switched the typescript target from `esnext` (oops) to `es2017`, which transpiles rest properties. Your issue should be fixed on `v2.1.1` 😁 

I'll see If I can automate some tests related to cross-browser support.

**Comment by TorstenDittmann** [comment]
@kaisermann Thank you alot! :blush: Can you say approximately when the version comes out? In a week I release an app which must necessarily run under Edge. Then at least I can plan and use a temporary solution.

**Comment by kaisermann** [comment]
Yes, of course! Approximately 25 minutes ago *wink wink*

**Comment by TorstenDittmann** [comment]
@kaisermann Uff, that was fast :grin: Thanks alot!

**Comment by kaisermann** [comment]
You're welcome! Let me know if your issue was fixed so I can close it here 🤙

**Comment by TorstenDittmann** [comment]
Everything worked flawless!
