### ISSUE TITLE
[!] Error: UMD and IIFE output formats are not supported for code-splitting builds. Error: UMD and IIFE output formats are not supported for code-splitting builds.

### ISSUE THREAD

**Issue by rlaferla** [kaisermann/svelte-i18n#48]
I'm getting this when I build:

```
[!] Error: UMD and IIFE output formats are not supported for code-splitting builds.
Error: UMD and IIFE output formats are not supported for code-splitting builds.
```

```$ yarn start:dev
yarn run v1.21.1
warning package.json: No license field
$ run-s build start
warning package.json: No license field
$ rollup -c

src/main.js → public/build/bundle.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/intl-messageformat/lib/core.js
4: See the accompanying LICENSE file for terms.
5: */
6: var __assign = (this && this.__assign) || function () {
                   ^
7:     __assign = Object.assign || function(t) {
8:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 1 other occurrence
node_modules/intl-messageformat/lib/formatters.js
1: var __extends = (this && this.__extends) || (function () {
                    ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
...and 3 other occurrences
node_modules/intl-format-cache/lib/index.js
4: See the accompanying LICENSE file for terms.
5: */
6: var __spreadArrays = (this && this.__spreadArrays) || function () {
                         ^
7:     for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
8:     for (var r = Array(s), k = 0, i = 0; i < il; i++)
...and 1 other occurrence

...and 3 other files```

**Comment by RemiKalbe** [comment]
How did you solve this issue?

**Comment by chovy** [comment]
I'm having this too.

**Comment by gavinr** [comment]
Same issue here - can we re-open this issue?

**Comment by kaisermann** [comment]
This is not an issue with `svelte-i18n`, but with your configuration of rollup. Please check how to use dynamic imports with your bundler 😁. I can make a section in the docs, but I don't have the time right now.

**Comment by gavinr** [comment]
Here is someone mentioning the problem in a rollup issue thread: https://github.com/rollup/rollup/issues/2463#issuecomment-455128513

**Comment by timohausmann** [comment]
I'm also getting this error following instructions from the [docs](https://github.com/kaisermann/svelte-i18n/blob/main/docs/Getting%20Started.md#32-asynchronous):

`register('en', () => import('./en.json'));`

I found these solutions:

- fallback to `addMessages` instead of `register`
- add output: { [inlineDynamicImports ](https://rollupjs.org/guide/en/#outputinlinedynamicimports): true } to your rollup.config.js 
- put i18n-files in /public and code your own funny little Promise loader like: 

```
register('en', function() {
    return window.fetch('/i18n/en.json')
        .then(data => data.json())
        .catch(error => console.log('i18n fetch error', error))
});
```

I don't wanna be a nagging b*tch but in my opinion this is a valid issue with this package if it doesn't provide an easy out-of-the-box solution that works with the very default Svelte+Rollup installation but requires a deep understanding of Rollup configs. If you let me know what's your go-to solution for dynamic imports with Svelte+Rollup I'll happily provide a PR for the docs.

**Comment by duongdominhchau** [comment]
At least JSON can be understood by JS engine without external library. Other formats like YAML is even worse, I have to either precompile it into JSON or add a library to decode it on the client side.

**Comment by kaisermann** [comment]
@timohausmann You're totally right! I should make it clearer the scenario where one can use dynamic imports or not. The lib was made with mostly Sapper in mind, which has built-in support for dynamic imports. A PR would be great! We could add a section in the [FAQ](https://github.com/kaisermann/svelte-i18n/blob/main/docs/FAQ.md) and some note in the getting started document.
