### ISSUE TITLE
Error: UMD and IIFE output formats are not supported for code-splitting builds.

### ISSUE THREAD

**Issue by chovy** [kaisermann/svelte-i18n#59]
Error: UMD and IIFE output formats are not supported for code-splitting builds.

get this error.

**Comment by kaisermann** [comment]
This is not a `svelte-i18n` issue. The IIFE and UMD formats are self-contained by definition, you can't export/import pieces of other UMD/IIFE because its contents are fully enclosed. -split.

If you're using rollup, which I assume you are, you have to use the ESM, AMD, or SystemJS format. Webpack doesn't have this problem because it has its runtime to replicate the import/export environment.
