### ISSUE TITLE
Escape characters are not working 

### ISSUE THREAD

**Issue by scerelli** [kaisermann/svelte-i18n#85]
**Describe the bug**
Escape characters do not works.

**Expected Behaviour**
I expect that using for example "\n" in a string creates a new line when rendered but it doesn't.

**Comment by KyteProject** [comment]
I was trying to get this working too, JSON uses \r instead of \n, but it doesn't work either.

This is obviously not a solution due to XSS concerns, but I am using svelte's {@html } to parse <br />'s inside the JSON string. The project is essentially just a static HTML site with localisation so it's not a big a risk for me.

**Comment by scerelli** [comment]
@KyteProject you can give a look at:

https://formatjs.io/docs/intl-messageformat-parser
https://formatjs.io/docs/intl-messageformat

**Comment by kaisermann** [comment]
The `formatjs` documentation uses a `react` example, which we can't follow 😅  Honestly, I'm not so sure how could we print a line break without using the `@html` modifier as this is out of the library's control.
